"""Initial migration

Revision ID: 7373b7673ef0
Revises: 
Create Date: 2024-10-18 00:05:43.062172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7373b7673ef0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'studies', ['name'])
    op.add_column('subjects', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'subjects', ['code'])
    op.create_unique_constraint(None, 'timecourses', ['path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timecourses', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_column('subjects', 'email')
    op.drop_constraint(None, 'studies', type_='unique')
    # ### end Alembic commands ###
