name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv sync --all-groups
    - name: Test with pytest
      run: |
        pytest expdb/tests/
